u_age = (input('What is your age?:'))
u_f_name = input ('What is your first name?:')
u_l_name = input ('What is your last name?:')
print ('Is',u_f_name.capitalize(),'really your first name?')
sel_y = (input('yes or no'))
if sel_y == ('yes') : print('Hello',u_f_name,u_l_name)
if sel_y == ('no') : print('lie') 
r_l_n = input('What is it then?')
print('hshshdhas') 